### ISSUE TITLE
Tagged data missing

### ISSUE THREAD

**Issue by domlatham** [Esukhia/derge-kangyur#8]
I'm not managing export the data using the scripts provided:
```
$ python3 toTei.py
transforming ../derge-kangyur-tags/001-tagged.txt
Traceback (most recent call last):
  File "toTei.py", line 148, in <module>
    parse_one_file(infilename, './output/UT4CZ5369-I1KG9'+str(volnum+126)+'/UT4CZ5369-I1KG9'+str(volnum+126)+'-0000.xml', volnum, options)
  File "toTei.py", line 119, in parse_one_file
    with open(infilename, 'r', encoding="utf-8") as inf:
FileNotFoundError: [Errno 2] No such file or directory: '../derge-kangyur-tags/001-tagged.txt'
```
It seems I'm missing a step to create tagged content in ../derge-kangyur-tags

**Comment by eroux** [comment]
should be fixed, can you give it a try?

**Comment by domlatham** [comment]
Yes, thank you.

The derge-tengyur has the same issue. Should I raise it seperately there?

**Comment by eroux** [comment]
just fixed it. There are a couple of places where there are errors in the markup in the Tengyur, I'll fix these once the review by NT's team is done. @ngawangtrinley when do you think that will happen?

**Comment by ngawangtrinley** [comment]
We're not touching the kangyur atm. We're a few weeks away from finishing comparing the Tengyur with Adarsha's last version. We'll then come back to it for some quick checks with the next incarnation of bospell. We're hoping to get the input done by Dzongsar in Tibet and do the same as we are doing now with Adarsha's Tengyur. @domlatham if you have a way to help with getting that input, that would be great! :D
It's all sponsored by KF and Cangioli had given Jeff a few volumes some years ago. We'll compare and improve both datasets of we get the files...
