### ISSUE TITLE
missed text?

### ISSUE THREAD

**Issue by eroux** [Esukhia/derge-kangyur#9]
84000 have 744a in their outline, starting page 265b of vol. 94, I believe it's beginning of b5. It seems alright to me, although it looks a bit like an addendum to the text.

**Comment by ngawangtrinley** [comment]
94!

**Comment by ngawangtrinley** [comment]
Situ Chojung just has one text in the karchak, so I guess it's two parts of a single text.

**Comment by ngawangtrinley** [comment]
It's just an a small addendum to the text, it doesn't figure in Situ Chojung's karchak and doesn't have a colophon so I'd count it as part of the text.

**Comment by eroux** [comment]
ok thanks!
